### ISSUE TITLE
Update generator to create default Fcrepo and Solr wrapper config files

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/hydra-head#339]
**STORY**
As a developer, I would like the hydra generator to provide config files for fcrepo_wrapper and solr_wrapper, so I can easily start those services for development and test environments with hydra-friendly settings.

**DETAILS**
We need a separate config file for development and test for solr_wrapper and fcrepo_wrapper - so four files total:

```
#config/solr_wrapper_development.yml
# version: 6.0.0
port: 8983
instance_dir: tmp/solr-development
collection:
    persist: true
    dir: solr/config
    name: hydra-development
```

```
#config/solr_wrapper_test.yml
# version: 6.0.0
port: 8985
instance_dir: tmp/solr-test
collection:
    persist: false
    dir: solr/config
    name: hydra-test
```

```
#config/fcrepo_wrapper_development.yml
port: 8984
enable_jms: false
fcrepo_home_dir: tmp/fcrepo4-development-data
```

```
#config/fcrepo_wrapper_test.yml.sample
port: 8986
enable_jms: false
fcrepo_home_dir: tmp/fcrepo4-test-data
```

**ACCEPTANCE**
- [ ] After I run the hydra generator, there is a solr_wrapper_test.yml generated in my ./config directory
- [ ] After I run the hydra generator, there is a solr_wrapper_development.yml generated in my ./config directory
- [ ] After I run the hydra generator, there is a fcrepo_wrapper_test.yml generated in my ./config directory
- [ ] After I run the hydra generator, there is a fcrepo_wrapper_development.yml generated in my ./config directory
